---
commitizen:
  bump_message: "chore(release): bump $current_version \u2192 $new_version [skip ci]"
  major_version_zero: true
  name: cz_conventional_commits
  tag_format: v$version
  update_changelog_on_bump: true
  version: 0.8.0
  version_files:
  - .cz.yaml:version
  - package.json:version
  version_scheme: semver
